version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./dbConf/conf.d:/etc/mysql/conf.d

  api:
    build:
      context: ./api
      args:
        DB_HOST: $DB_HOST
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
        HOST: $HOST
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        FOG_DIRECTORY: $FOG_DIRECTORY
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      - api-bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build:
      context: ./front
      args:
        API_URL: $API_URL
        HOST: $HOST
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
        FIREBASE_SENDER_ID: $FIREBASE_SENDER_ID
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_MEASUREMENT_ID: $FIREBASE_MEASUREMENT_ID
        GMAP_API_KEY: $GMAP_API_KEY
    command: sh -c "yarn start"
    ports:
      - "$FRONT_PORT:3000"
    volumes:
      - ./front:/front
      - front-node_modules:/front/node_modules
    depends_on:
      - api
    tty: true

volumes:
  db-volume:
  api-bundle:
    driver: local
  front-node_modules:
