version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./dbConf/conf.d:/etc/mysql/conf.d

  api:
    build:
      context: ./api
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      - api-bundle:/usr/local/bundle
    depends_on:
      - db

  front:
    build: ./front
    command: sh -c "yarn start"
    ports:
      - "8000:3000"
    volumes:
      - ./front:/front
      - front-node_modules:/front/node_modules
    depends_on:
      - api

volumes:
  db-volume:
  api-bundle:
    driver: local
  front-node_modules:
